import React from 'react';
import { Video } from '../../components/Video';
import './Projects.scss';
import fishyCat from '../../images/fishyCatDemo2.mp4';
import honkNHurdle from '../../images/honkNHurdle.mp4';
import simonSays from '../../images/simonSays.mp4';

const Projects = () => {
    return (
        <div>
            <div className='main-projects'>
                <div className='projects-text'>
                    Projects
                </div>
                <div className="h-64 flex grid grid-cols-2">
                    {/* Section 1 */}
                    <div className="project-container flex-1 pr-10">
                        <div className='projects-title'>Honk n Hurdle</div>
                        <hr className='border-black'></hr>
                        <div className='projects-description'>
                            An infinite 2D runner game where players play as a goose dodging obstacles while chasing a student on the University of Waterloo campus.
                        </div>
                    </div> 
                    <div className="text-white flex-1 p-10">
                        <Video src={honkNHurdle} id="video1" ratio='4_3'/>
                    </div>

                    {/* Section 2 */}
                    <div className="project-container flex-1 pr-10">
                        <div className='projects-title'>Simon Says</div>
                        <hr className='border-black'></hr>
                        <div className='projects-description'>
                            An implementation of the classic Simon Says game. Players must mimic a button sequence generated by the computer in the exact order to advance to the next level.
                        </div>
                    </div> 
                    <div className="text-white flex-1 p-10"><Video src={simonSays} id="video2" ratio='4_3'/></div>

                    {/* Section 3 */}
                    <div className="project-container flex-1 pr-10">
                        <div className='projects-title'>Fishy Cat</div>
                        <hr className='border-black'></hr>
                        <div className='projects-description'>
                            Players play as a charming feline protagonist on a journey to catch a variety of fish in order to collect new cat friends and earn coins.
                        </div>
                    </div> 
                    <div className="text-white flex-1 p-10">
                        <Video src={fishyCat} id="video3" ratio='4_3'/>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default Projects



