import React from 'react';
import { Video } from '../../components/Video';
import './Projects.scss';
import fishyCat from '../../images/fishyCatDemo2.mp4';
import honkNHurdle from '../../images/honkNHurdle.mp4';
import simonSays from '../../images/simonSays.mp4';
import janescamera from '../../images/janescamera.mp4';

const Projects = () => {
    return (
        <div>
            <div className='main-projects'>
                <div className='projects-text'>
                    Projects
                </div>
                <div className="h-64 flex grid grid-cols-2">
                    {/* Section 1 */}
                    <div className="project-container flex-1 pr-10">
                        <div className='projects-title'>
                            <a href="https://janeyao.itch.io/fishy-cat-v2" rel="noreferrer">Fishy Cat</a>
                            <div className='wrapper'><div className='projects-tools'>Unity | C#</div></div>
                        </div>
                        <hr/>
                        <div className='projects-description'>
                            Players play as a charming feline protagonist on a journey to catch a variety of fish in order to collect new cat friends and earn coins.
                        </div>
                    </div> 
                    <div className="text-white flex-1 p-10">
                        <Video src={fishyCat} id="video1" ratio='4_3'/>
                    </div>

                    {/* Section 2 */}
                    <div className="project-container flex-1 pr-10">
                        <div className='projects-title'>
                            <a href="https://janeyao.itch.io/honk-n-hurdle" rel="noreferrer">Honk n Hurdle</a>
                            <div className='wrapper'><div className='projects-tools'>Unity | C#</div></div>
                        </div>
                        <hr/>
                        <div className='projects-description'>
                            An infinite 2D runner game where players play as a goose dodging obstacles while chasing a student on the University of Waterloo campus.
                        </div>
                    </div> 
                    <div className="text-white flex-1 p-10">
                        <Video src={honkNHurdle} id="video2" ratio='4_3'/>
                    </div>

                    {/* Section 3 */}
                    <div className="project-container flex-1 pr-10">
                        <div className='projects-title'>
                            <a href="https://deft-beignet-abf8a7.netlify.app/" rel="noreferrer">Simon Says</a>
                            <div className='wrapper'><div className='projects-tools'>TypeScript | Vite</div></div>
                        </div>
                        <hr/>
                        <div className='projects-description'>
                            An implementation of the classic Simon Says game. Players must mimic a button sequence generated by the computer in the exact order to advance to the next level.
                        </div>
                    </div> 
                    <div className="text-white flex-1 p-10"><Video src={simonSays} id="video3" ratio='4_3'/></div>

                    {/* Section 4 */}
                    <div className="project-container flex-1 pr-10">
                        <div className='projects-title'>
                            <a href="https://deft-beignet-abf8a7.netlify.app/" rel="noreferrer">Photography Site</a>
                            <div className='wrapper'><div className='projects-tools'>JavaScript</div></div>
                        </div>
                        <hr/>
                        <div className='projects-description'>
                        A personal photography site that celebrates the essence of minimalistic photography. Immerse yourself in a serene visual experience captured and curated by me throughout my high school and post-secondary years :)
                        </div>
                    </div> 
                    <div className="text-white flex-1 p-10"><Video src={janescamera} id="video4" ratio='4_3'/></div>
                </div>
            </div>
        </div>
    )
}

export default Projects



